### ISSUE TITLE
AssertionError: datasets should not be an empty iterable

### ISSUE THREAD

**Issue by tongleyan** [chuangchuangtan/NPR-DeepfakeDetection#20]
2024_09_17_08_51_35
(0 AttGAN      ) acc: 64.8; ap: 73.0
(1 InfoMaxGAN  ) acc: 53.1; ap: 61.2
(2 MMDGAN      ) acc: 53.1; ap: 62.6
(3 RelGAN      ) acc: 98.6; ap: 100.0
Traceback (most recent call last):
  File "/root/share/NPR-DeepfakeDetection-main/test.py", line 69, in <module>
    acc, ap, _, _, _, _ = validate(model, opt)
  File "/root/share/NPR-DeepfakeDetection-main/validate.py", line 10, in validate
    data_loader = create_dataloader(opt)
  File "/root/share/NPR-DeepfakeDetection-main/data/__init__.py", line 44, in create_dataloader
    dataset = get_dataset(opt)
  File "/root/share/NPR-DeepfakeDetection-main/data/__init__.py", line 26, in get_dataset
    return torch.utils.data.ConcatDataset(dset_lst)

**Comment by tongleyan** [comment]
Hello author, how can this issue be resolved?
